### ISSUE TITLE
Error in test.py file while running with demonstrations

### ISSUE THREAD

**Issue by Mihir3009** [Alrope123/rethinking-demonstrations#4]
I correctly set up the environment and it's running for zero_shot.

But, I am running the following command: 
`python test.py --dataset tweet_eval-hate --gpt2 gpt2-large --method direct --out_dir out/gpt2-large --use_demonstrations --k 16 --seed 100,13,21,42,87`

However, I am getting this error:

```
10/19/2022 15:15:53 - INFO - __main__ - Namespace(checkpoint=None, dataset='tweet_eval-hate', do_zeroshot=False, global_step=None, gpt2='gpt2-large', is_null=False, k=16, log_file=None, method='direct', out_dir='out/gpt2-large', seed='100,13,21,42,87', split='test', task=None, test_batch_size=64, unseen_domain_only=False, use_calibration=False, use_demonstrations=True, use_random_english_words=False)
Traceback (most recent call last):
  File "test.py", line 274, in <module>
    main(logger, args)
  File "test.py", line 44, in main
    assert args.global_step is not None
AssertionError
```

Can you please help me with this error?

**Comment by shmsw25** [comment]
I think you forgot to specify `--do_zeroshot`. Would you specify it and see if you still get an error?

FYI, see [README](https://github.com/Alrope123/rethinking-demonstrations/#no-demonstrations) for the exact command line!
