### ISSUE TITLE
UnboundLocalError: local variable 'new_dataset_dir' referenced before assignment

### ISSUE THREAD

**Issue by raymondzmc** [Alrope123/rethinking-demonstrations#7]
I got the following message after running the code to generate random labels:

`python create_data.py --variant random --dataset commonsense_qa`

**Comment by sleeepeer** [comment]
I met with the same problem, the following line can fix it.
at line 56, assign new_dataset_dir
```python
for dataset_idx, (dataset, new_dataset) in enumerate(zip(datasets, new_datasets)):
    new_dataset_dir = os.path.join(args.data_dir, new_dataset)
    if not os.path.exists(new_dataset_dir):
        os.mkdir(new_dataset_dir)
```
at line 225, change the 'w' to 'w+'
```python
# write the modified data
with open(os.path.join(new_dataset_dir, "{}_{}_{}_{}.jsonl".format(new_dataset, args.k, seed, "train")), "w+") as f:
    for dp in train_data:
        f.write(json.dumps(dp))
        f.write("\n")
```
maybe you should also create a config file for the new dataset:
```python
    with open(os.path.join(config_file, "{}.json".format(new_dataset)), "w") as f:
        json.dump(config, f)
```

**Comment by Alrope123** [comment]
Sorry about the bug. It was due to the missing "not" [here](https://github.com/Alrope123/rethinking-demonstrations/blob/970c28aaeb7b7ba2094c867ac15d2a8aea41a9c1/create_data.py#L66). It's not fixed with the latest push.
